[package]
name = "pr-checkout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
mockito = "0.30.0"

[[bin]]
name = "pr-checkout"
path = "main.rs"
